[template]
cargo_generate_version = ">=0.10.0"
exclude = [
    "src-tauri/icons/**/*",
]
ignore = [
    "actix/**/*",
]

[placeholders]
project_description = { prompt = "Enter project description", default = "TAVERN Stack Template", type = "string" }
author = { prompt = "Enter the authors name", default = "", type = "string" }
repository = { prompt = "Enter the repository URL", default = "", type = "string" }
app_identifier = { type = "string", prompt = "Enter the app identifier (e.g., com.yourcompany.appname)", default = "com.tauri.app" }
window_title = { type = "string", prompt = "Enter the window title", default = "{{crate_name}}" }
window_width = { type = "string", prompt = "Enter the window width", default = "800" }
window_height = { type = "string", prompt = "Enter the window height", default = "600" }

