[template]
cargo_generate_version = ">=0.10.0"
sub_templates = ["actix", "tauri"]

[placeholders]
project_description = { prompt = "Enter project description", default = "TAVERN Stack Template", type = "string" }
author = { prompt = "Enter the authors name", default = "", type = "string" }
repository = { prompt = "Enter the repository URL", default = "", type = "string" }
sub_template = { type = "string", prompt = "Which template variant would you like?", choices = ["actix", "tauri"], default = "actix" }

[conditional.'sub_template == "actix"'.placeholders]
api_port = { type = "string", prompt = "What port should the API server run on?", default = "1421" }

[conditional.'sub_template == "tauri"'.placeholders]
app_identifier = { type = "string", prompt = "Enter the app identifier (e.g., com.yourcompany.appname)", default = "com.tauri.app" }
window_title = { type = "string", prompt = "Enter the window title", default = "{{crate_name}}" }
window_width = { type = "string", prompt = "Enter the window width", default = "800" }
window_height = { type = "string", prompt = "Enter the window height", default = "600" }

[conditional.'sub_template == "actix"']
ignore = [
    "tauri/**/*",
]
exclude = [
    "tauri/**/*",
]
raw = [
    "actix/src/assets/providers/ThemeProvider.tsx",
    "actix/src-actix/main.rs",
]

[conditional.'sub_template == "tauri"']
ignore = [
    "actix/**/*",
]
exclude = [
    "actix/**/*",
]